-- 코드를 작성해주세요
WITH CTE(ID,R,TOTAL)
AS (
    SELECT ID,
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R,
        COUNT(*) OVER () AS TOTAL
    FROM ECOLI_DATA
)
SELECT ID,
    CASE
        WHEN R <= TOTAL * 0.25 THEN "CRITICAL"
        WHEN R <= TOTAL * 0.5 THEN "HIGH"
        WHEN R <= TOTAL * 0.75 THEN "MEDIUM"
        ELSE "LOW"
    END AS COLONY_NAME
FROM CTE
ORDER BY ID